#!/usr/bin/env node
"use strict";var e=require("meow"),t=require("update-notifier"),r=require("cosmiconfig"),a=require("is-git-repository"),i=require("redent"),s=require("gradient-string"),o=require("chalk"),l=require("nodegit"),n=require("async/eachOfSeries");function c(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var g=c(e),d=c(t),u=c(a),f=c(i),h=c(s),w=c(o),p=c(n),y=e=>[Object,Array].includes((e||{}).constructor)&&!Object.entries(e||{}).length;const m=require("deepmerge");async function C(e={twd:".",rules:{}}){const{twd:t,rules:r}=m({twd:".",rules:{"alias.ls":"ls-files","alias.remotes":"remote -v","alias.amend":"!git log -n 1 --pretty=tformat:%s%n%n%b | git commit -F - --amend","alias.fixup":"commit --fixup=HEAD","core.ignorecase":"false","alias.s":"status","alias.p":"push","alias.b":"branch -a -v","alias.cm":"commit -m","alias.tags":"tag -l","alias.co":"checkout","alias.all":"add -A","alias.pl":"pull --ff-only","alias.stashes":"stash list","alias.med":"merge develop","alias.mem":"merge master","alias.l":"log --oneline --color -6","alias.out":"log @{u}..","alias.la":"log -16 --color=always --all --topo-order --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative","alias.ll":"log --color=always --all --topo-order --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit","alias.lg":"log -10 --color=always --all --graph --topo-order --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative","alias.lgl":"log --color=always --all --graph --topo-order --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit","alias.wdiff":"diff --color-words"}},e),a=await async function(e){const t=await l.Repository.open(e);return await t.config()}(t);await async function(e,t){await p.default(t,(async(t,r)=>{await e.setString(r,t)}))}(a,r)}class b{constructor(){var e;d.default({pkg:{name:"setgit-cli",version:"1.1.2"}}).notify(),this.cli=g.default("\n      使用方式\n        $ setgit [工作目录，默认：'process.cwd()']\n\n      选项\n        --version, -v                              查看版本号\n        --help, -h                                 查看帮助\n\n      示例\n        $ setgit                                   为当前工作目录配置 Git\n        $ setgit /usr/pro/api.name.io              为指定工作目录配置 Git\n\n      提示\n        检测到用户未提供自定义配置时，`setgit` 将会使用默认配置，详情参见\n        https://github.com/iTonyYo/setgit-cli#配置。\n    ",{flags:{version:{type:"boolean",alias:"v"},help:{type:"boolean",alias:"h"}}}),this.workingPath=(e=this.cli.input[0],{twd:y(e)?process.cwd():e,cwd:process.cwd()}).twd,this.userDefinedConfig=this.getUserDefinedConfig()}async run(){u.default(this.workingPath)?(await C({twd:this.workingPath,rules:this.userDefinedConfig}),this.success()):this.error()}success(){y(this.userDefinedConfig)?console.log(f.default(w.default`
        {bold ${h.default.rainbow("操作成功!")}}
        {grey 检测到您未提供自定义配置，\`setgit\` 使用了默认配置。}

        {grey 操作目录：}
        {grey ${this.workingPath}}
      `)):console.log(f.default(w.default`
      {greenBright.bold ${h.default.rainbow("操作成功!")}}

      {grey 操作目录：}
      {grey ${this.workingPath}}
    `))}error(){console.error(f.default(w.default`
      {redBright.bold 这不是一个 Git 仓库!}

      {grey 操作目录：}
      {grey ${this.workingPath}}
    `))}getUserDefinedConfig(){const e=r.cosmiconfigSync("git").search(this.workingPath);return y(e)?{}:((e,t,r=null)=>String.prototype.split.call(t,/[,[\].]+?/).filter(Boolean).reduce(((e,t)=>Object.hasOwnProperty.call(e,t)?e[t]:r),e))(e,"config")}}(async()=>{try{const e=new b;await e.run()}catch(e){throw e}})();
